language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - echo "--- Tests ---"
  - python -m pytest -v --cov=dags --cov-branch tests/